version: '3.9'

services:
  rabbitmq:
   image: rabbitmq:3-management
   container_name: rabbitmqtest
   ports:
     - 5672:5672
     - 15672:15672
   environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
  fodbold:
    image: ${DOCKER_REGISTRY-}fodbold
    build:
      context: .
      dockerfile: Fodbold/Dockerfile
    volumes:
      - counter_data:/counter_volume
  montyhall:
    image: ${DOCKER_REGISTRY-}montyhallapp
    build:
        context: .
        dockerfile: MontyHallApp/Dockerfile
  vaekkeur:
    image: ${DOCKER_REGISTRY-}vaekkeur
    build:
        context: .
        dockerfile: Vaekkeur/Dockerfile
volumes:
  counter_data: